### ISSUE TITLE
IUA Refresh token handling

### ISSUE THREAD

**Issue by oliveregger** [ehealthsuisse/ch-epr-mhealth#20]
Refresh token handling needs to be defined if allowed or not (refresh without authentication possible).

**Comment by msmock** [comment]
We won't allow refresh token, since their lifetime management is quite difficult.

**Comment by oliveregger** [comment]
we are waiting currently on feedback

**Comment by limux82** [comment]
# Proposal for Using Refresh Tokens in ITI-71

Since ITI-71 is derived from the OAuth2 flow, we believe that it should adhere to the secure mechanisms provided by the standard, specifically the **refresh token mechanism** for obtaining new access tokens.

The decision to **prohibit the use of refresh tokens for IUA tokens** has significant practical implications for both **web applications** and **mobile apps**:

## 1. Loss of Application State in Web Applications
Redirecting the browser to the Authorization Server for a new authentication session each time the IUA token expires can lead to a **loss of application state**.

- In **JavaScript-based frontend applications**, where active state (e.g., form data, user selections, in-memory data) is maintained, a forced redirection causes **frustration and disrupts** the user experience.

## 2. User Experience Impact
- **Mobile Applications:** Opening an **external browser** for authentication is **impractical and highly disruptive**.
- **Web Applications:** Redirecting the user to the Authorization Server and then back to the application **breaks the user flow**.  Additionally, the **page state must be reloaded**, which can cause delays, especially on **low-bandwidth connections**.

## 3. Benefits and Security of Refresh Tokens
- **Refresh tokens** provide a **secure and standardized** method to obtain new access tokens **without disrupting the user flow**.
- **Rotating refresh tokens** significantly reduce security risks:
  - Each refresh token is **valid only once**, minimizing the impact of potential token leaks.
  - The **lifetime of the refresh token** can be generally configured in the Authorization Server, aligning it with the session duration.
  - A **maximum duration** for the refresh token can be defined to further control security.

## Conclusion
Prohibiting refresh tokens unnecessarily **complicates the authentication flow** for both **end users** and **developers**.

We propose a **reevaluation of this decision**, considering additional security measures such as:

✅ **Rotating refresh tokens** – ensuring security while maintaining a seamless user experience.  
🔗 [OAuth 2.1 Refresh Token Endpoint Extension](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-12#refresh-token-endpoint-extension)  

✅ **PKCE (Proof Key for Code Exchange)** in the Authorization Code grant – increasing protection against attacks.  
🔗 [RFC 7636 - PKCE](https://datatracker.ietf.org/doc/html/rfc7636#page-8)  

By adopting these security enhancements, we can achieve **both security and usability** without sacrificing user experience.

**Comment by jkiddo** [comment]
FYI @oliveregger @msmock - @limux82 represents the 'Trifork' case here.

**Comment by msmock** [comment]
An  IUA authorization server may not create an new authorization token, without verifying the user has a running session with 
the identity provider. Currently annex 8 does not allow refresh token. The identity provider involved in the discussion agreed upon not to add the refresh token due to security problems. We currently see no way to fulfill the requirement to validate the users IDP session other than to enforce re-authentication via the client browser.

But even if we had a OpenID Connect refresh token, the implementation would be cumbersome. If the IUA authorization server uses a refresh token via the backchannel the session information on the authorization server and browser cookie gets out of synch. 

The recommendation in the literature is to avoid useability problems with (hidden) IFrames. Is that impractical from your point of view?

**Comment by limux82** [comment]
Yes, it is impractical. Silent authentication is highly discouraged: modern browsers block silent authentication using iframes due to tightened security measures (such as SameSite policies and third-party cookie restrictions). This method is unreliable, and mobile apps cannot support it at all since you simply cannot have an iframe in a mobile app. For this reason, many OIDC vendors recommend using PKCE along with rotating refresh tokens.
That said, the refresh token mechanism remains essential between the client and the authorization service. Regarding verifying that the IDP session is still active, most IDPs currently support SAML and offer a defined SAML renew action. We can feasibly perform a SAML renew with the IDP at the moment of the OIDC token refresh between the Authorization Client and Authorization Server. This approach ensures that the IDP session remains active. Moreover, ITI‑71 should permit the connection between the Authorization Server and the IDP to also use SAML (see [GitHub Issue #258](https://github.com/ehealthsuisse/ch-epr-fhir/issues/258)), allowing us to maintain only OIDC between the Authorization Client and Server (in this way we don't have impact on SmartOnFhir).
Additionally, several market solutions exist that can update cookies during token refresh, ensuring that cookies remain in sync with the new tokens.

**Comment by msmock** [comment]
With allowing SAML Identity Assertions identifying the user when retrieving an IUA access token, primary systems and portals can use the IdP renew transaction to retrieve an updated IdP assertion, which they can use to get a new IUA access token. The situation is the same we work with XDS.b and XUA for years now. With this mechanism we have a clear separation of the responsibility. I can hardly justify to specify an extra mechanism to refresh an IUA access token which mixes the responsibilities. 

When the primary system or portal uses Open ID Connect for user authentication, it can also present the IdP token identifying the user when retrieving an IUA access token. The Open ID Connect protocol used in the EPR does not support refresh token. This has been discussed in a working group with delegates from all communities, all IdP and all platform provider. In the discussion the consensus was not to support a refresh token, thus the client shall re-authenticate the user at the identity provider running the authorization code flow. I can hardly justify to specify an extra mechanism to refresh an IUA access token, when the client used open id connect and the IUA authorization server uses a WS Trust refresh transaction with SAML. 

The same applies to SMART on FHIR variants, where the IUA Authorization Server takes the role of a OpenID Connect client application server. If the IdP token is no longer valid, the IUA Authorization Server shall redirect the user agent to the identity provider, since in the EPR the OpenID Connect refresh flow is not supported. 

If you want the OpenID Connect specification for the EPR to support the refresh flow, you must raise an issue to change Annex 8. But take into account, that the change requires the approval of all IdP and will take time to implement. To raise the issue, you can place it at the "Steuerung Weiterentwicklung EPD".
